# Use Python 3.7.2 as base image
FROM python:3.7.2

# Set working directory
WORKDIR /app

# Add code to docker image
ADD . /app

# Install python modules
RUN pip3 install -r requirements.txt

ENV PORT 8080

# Start uWSGI
CMD ["gunicorn", "app:app", "--config=config.py"]
